twitter_client:
  consumer_key: "mhCWQ6xD08VXMIylJIZ98AXxh"
  consumer_secret: "aawJm8w2XLrbHQO6SxYgKY4ii7ElNH97i4zGDx7V3IrCrQvAIR"
  access_token: "800644619465670656-P832RHheNPDqT9zECCQyn6ZQPIYjwLa"
  access_token_secret: "mrLqeqVgiziDK3P0aQPI5euBkvxkS8ANGflN1OSp2SlGs"
